core: Fix compilation error
main_unix.cpp:95:31: error: ‘class QStringBuilder<QString, QString>’ has
no member named ‘toLocal8Bit’

I didn't test it as I cannot reproduce this error. But it should help.

Regression since 30b1daf02fb1bb85d00e12844b75add73483c374.

Reported-by: Piotr Dąbrowski <ultr@ultr.pl>
Signed-off-by: Bartosz Brachaczek <b.brachaczek@gmail.com>